baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "flowtheme"
[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = ""
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = ""
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    pre = ""
    url = "/contact/"
    weight = 4