baseURL = "/"
languageCode = "en-us"
title = "Flow Driving School"
theme = "flowtheme"
summaryLength = 50
[menu]
  [[menu.main]]
    name = "Home"
    pre = ""
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = ""
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name="About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    pre = ""
    url = "/contact/"
    weight = 4 